Django/django-practice/Django_practice_0330/practices/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

Django/django-practice/Django_practice_0330/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/completed/', views.completed, name='completed'),
]

Django/django-practice/Django_practice_0330/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

Django/django-practice/Django_practice_0330/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    todo = Todo.objects.all()
    context = {
        'todo': todo
    }
    return render(request, 'index.html', context)


def new(request):
    return render(request, 'new.html')


def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    priority = request.POST.get('priority')
    deadline = request.POST.get('deadline')
    todo = Todo(title=title, content=content, priority=priority, deadline=deadline)
    todo.save()
    return redirect('todos:detail', todo.pk)


def detail(request, pk):
    todo = Todo.objects.get(pk=pk)
    context = {
        'todo': todo
    }
    return render(request, 'detail.html', context)


def delete(request, pk):
    todo = Todo.objects.get(pk=pk)
    todo.delete()
    return redirect('todos:index')


def edit(request, pk):
    todo = Todo.objects.get(pk=pk)
    context = {
        'todo': todo
    }
    return render(request, 'edit.html', context)


def update(request, pk):
    todo = Todo.objects.get(pk=pk)
    todo.title = request.POST.get('title')
    todo.content = request.POST.get('content')
    todo.priority = request.POST.get('priority')
    todo.deadline = request.POST.get('deadline')
    todo.save()
    return redirect('todos:detail', todo.pk)


def completed(request, pk):
    todo = Todo.objects.get(pk=pk)
    if todo.completed == True:
        todo.completed = False
        todo.save()
    else:
        todo.completed = True
        todo.save()
    return redirect('todos:index')

Django/django-practice/Django_practice_0330/todos/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  <title>Index</title>
</head>
<body>
  <div class="container m-3 p-5" style="width:500px">
    <h1 class="mb-3">🔥{{ todo.title }}</h1>
    <ul class="list-group mb-3">
      <li class="list-group-item">할 일 내용: {{ todo.content }}</li>
      <li class="list-group-item">우선순위: {{ todo.priority }}</li>
      <li class="list-group-item">마감기한: {{ todo.deadline|date:"Y년 m월 d일" }}</li>
      <li class="list-group-item">완료여부: {{ todo.completed }}</li>
    </ul>
    <div class="d-flex justify-content-between">
      <a href="{% url 'todos:edit' todo.pk %}">
        <button type="button" class="btn btn-primary mb-3">수정</button>
      </a>
      <form action="{% url 'todos:delete' todo.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mb-3">삭제</button>
      </form>
    </div>
    <a href="{% url 'todos:index' %}">
      <button type="button" class="btn btn-warning mb-3">돌아가기</button>
    </a>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>

Django/django-practice/Django_practice_0330/todos/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  <title>New</title>
</head>
<body>
  <div class="container m-3 p-5" style="width:500px">
    <form action="{% url 'todos:update' todo.pk %}" method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="title" class="form-label">할 일 제목</label>
        <input type="text" class="form-control" id="title" name="title" value="{{ todo.title }}">
      </div>
      <div class="mb-3">
        <label for="content" class="form-label">할 일 내용</label>
        <textarea class="form-control" id="content" name="content" rows="10">{{ todo.content }}</textarea>
      </div>
      <div class="mb-3">
        <label for="priority" class="form-label">우선순위</label>
        <input type="number" class="form-control" id="priority" min='1' name="priority" value="{{ todo.priority }}">
      </div>
      <div class="mb-3">
        <label for="deadline" class="form-label">마감기한</label>
        <input type="date" class="form-control" id="deadline" name="deadline" value="{{ todo.deadline|date:"Y-m-d" }}">
      </div>
      <button type="submit" class="btn btn-primary mb-3">수정</button>
    </form>
    <a href="{% url 'todos:index' %}">
      <button type="button" class="btn btn-warning">돌아가기</button>
    </a>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>

Django/django-practice/Django_practice_0330/todos/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  <title>Index</title>
</head>
<body>
  <div class="container m-3 p-5 align-items-center" style="width:500px">
    <h1 class="mb-3">⚡To-do List</h1>
    <ul class="list-group mb-3">
      {% for thing in todo %}
        <div class="list-group-item">
          <a href="{% url 'todos:detail' thing.pk %}">{{ thing.title }}</a>
          {% if thing.completed == True %}
            <p class="float-end m-0">완료 ⭕ <a href="{% url 'todos:completed' thing.pk %}">완료 취소</a></p>
          {% else %}
            <p class="float-end m-0">완료 ❌ <a href="{% url 'todos:completed' thing.pk %}">완료 표시</a></p>
          {% endif %}
          
        </div>
      {% endfor %}
    </ul>
    
    <a class="btn btn-outline-primary mb-3" href="{% url 'todos:new' %}" role="button">할 일 추가</a>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>

Django/django-practice/Django_practice_0330/todos/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  <title>New</title>
</head>
<body>
  <div class="container m-3 p-5" style="width:500px">
    <form action="{% url 'todos:create' %}" method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="title" class="form-label">할 일 제목</label>
        <input type="text" class="form-control" id="title" name="title">
      </div>
      <div class="mb-3">
        <label for="content" class="form-label">할 일 내용</label>
        <textarea class="form-control" id="content" name="content" rows="10"></textarea>
      </div>
      <div class="mb-3">
        <label for="priority" class="form-label">우선순위</label>
        <input type="number" class="form-control" id="priority" min='1' name="priority">
      </div>
      <div class="mb-3">
        <label for="deadline" class="form-label">마감기한</label>
        <input type="date" class="form-control" id="deadline" name="deadline" value="2023-03-30">
      </div>
      <button type="submit" class="btn btn-outline-primary mb-3">생성</button>
    </form>
    <a href="{% url 'todos:index' %}">
      <button type="button" class="btn btn-outline-warning">돌아가기</button>
    </a>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>