Django/django-project/PJT-04(balance-game)/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

Django/django-project/PJT-04(balance-game)/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/django-project/PJT-04(balance-game)/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
     path('', views.index, name='index'),
     path('create/', views.create, name='create'),
     path('<int:post_pk>/', views.detail, name='detail'),
     path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
     path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
     path('<int:post_pk>/delete/', views.delete, name='delete'),
     path('<int:post_pk>/update/', views.update, name='update'),
     path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
     path('<int:post_pk>/likes/', views.likes, name='likes'),
     path('<int:post_pk>/comments/<int:comment_pk>/comment_likes/', views.comment_likes, name='comment_likes'),
]

Django/django-project/PJT-04(balance-game)/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings


# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_posts')
    title = models.CharField(max_length=20)
    select1_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='selected1_users', blank=True)
    select1_content = models.CharField(max_length=20)
    select2_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='selected2_users', blank=True)
    select2_content = models.CharField(max_length=20)
    image1 = ProcessedImageField(blank=True, null=True,
                                upload_to='image/',
                                processors=[ResizeToFill(260, 300)],
                                format='JPEG',
                                options={'quality': 90})
    image2 = ProcessedImageField(blank=True, null=True,
                                upload_to='image/',
                                processors=[ResizeToFill(260, 300)],
                                format='JPEG',
                                options={'quality': 90})


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)

Django/django-project/PJT-04(balance-game)/posts/forms.py
from django import forms
from .models import Post, Comment
from django.forms.widgets import FileInput


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'select1_content', 'image1', 'select2_content', 'image2')
        label_suffix = ''

    title = forms.CharField(label='주제', label_suffix='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'style': 'width: 200px;'}))
    select1_content = forms.CharField(label='옵션1', label_suffix='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'style': 'width: 200px;'}))
    select2_content = forms.CharField(label='옵션2', label_suffix='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'style': 'width: 200px;'}))
    image1 = forms.ImageField(label='옵션1 이미지', label_suffix='', required=False, widget=forms.ClearableFileInput(
        attrs={'class': 'form-control-file'}))
    image2 = forms.ImageField(label='옵션2 이미지', label_suffix='', required=False, widget=forms.ClearableFileInput(
        attrs={'class': 'form-control-file'}))


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'placeholder': '댓글 작성',
                'class': 'form-control',
                'style': 'width: 80%; display: inline-flex;',
            },
        ),
    )

    class Meta:
        model = Comment
        fields = ('content',)
        label_suffix = ''

Django/django-project/PJT-04(balance-game)/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.conf import settings
import os


def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm()

    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)


@login_required
def answer(request, post_pk, answer):
    post = Post.objects.get(pk=post_pk)
    user1 = post.select1_users.all()
    user2 = post.select2_users.all()
    if request.user not in user1 and request.user not in user2:
        if answer == 'select1':
            post.select1_users.add(request.user)
        elif answer == 'select2':
            post.select2_users.add(request.user)

    return redirect('posts:detail', post.pk)


def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comment_form = CommentForm()
    comments = post.comment_set.all()
    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user == post.user:
        if post.image1:  
            image1_path = os.path.join(settings.MEDIA_ROOT, str(post.image1))
            if os.path.isfile(image1_path):
                os.remove(image1_path)
        if post.image2:  
            image2_path = os.path.join(settings.MEDIA_ROOT, str(post.image2))
            if os.path.isfile(image2_path):
                os.remove(image2_path)
        post.delete()
    return redirect('posts:index')


@login_required
def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user != post.user:
        return redirect('posts:index')  

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        print(request.FILES)
        if request.FILES.get('image1', None) != None:
            image1_path = os.path.join(settings.MEDIA_ROOT, str(post.image1))
            if os.path.isfile(image1_path):
                os.remove(image1_path)
        if request.FILES.get('image2', None) != None: 
            image2_path = os.path.join(settings.MEDIA_ROOT, str(post.image2))
            if os.path.isfile(image2_path):
                os.remove(image2_path)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm(instance=post)

    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/update.html', context)


@login_required
def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.user = request.user
        comment.save()
        return redirect('posts:detail', post.pk)
    else:
        comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def comment_delete(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()

    return redirect('posts:detail', post_pk)


@login_required
def likes(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if post.like_users.filter(pk=request.user.pk).exists():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    return redirect('posts:detail', post.pk)


@login_required
def comment_likes(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if comment.like_users.filter(pk=request.user.pk).exists():
        comment.like_users.remove(request.user)
    else:
        comment.like_users.add(request.user)
    return redirect('posts:detail', post_pk)

Django/django-project/PJT-04(balance-game)/posts/templates/posts/create.html
{% extends 'base.html' %}
{% block title %}밸런스 게임 생성{% endblock title %}
{% block style %}
{% endblock style %} 
{% block body %}
<h2 class="mb-3">🎮 밸런스 게임 생성</h2>
<form
  action="{% url 'posts:create' %}"
  method="POST"
  enctype="multipart/form-data"
>
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="생성" class="btn btn-outline-primary" />
</form>
{% endblock body %}

Django/django-project/PJT-04(balance-game)/posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}detail{% endblock title %}
{% block style %}
{% comment %} 
.card {
  width : 348px;
  height: 332px;
} {% endcomment %}

.card-footer a {
  font-weight: normal;
}

.card-footer {
  height: 43px;
}
.card-footer-input {
  line-height: 43px;
}


{% endblock style %} 
{% block body %}

<div class="mb-3 d-flex justify-content-between align-items-center">
  <div class="col-sm-8">
    <h2 class="mb-0 d-flex">🤼 {{ post.title }}
      {% comment %} <form action="{% url 'posts:likes' post.pk %}" method='POST'>
        {% csrf_token %}
        <button class="border-0 bg-transparent" type ='submit'>
          <i class="bi bi-hand-thumbs-up"></i>
        </button>
      </form> {% endcomment %}
      <form action="{% url 'posts:likes' post.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in post.like_users.all %}
            <button class="border-0 bg-transparent" type="submit" value="좋아요">
              <i class="bi bi-hand-thumbs-up text-primary"></i>
            </button>
        {% else %}
            <button class="border-0 bg-transparent" type="submit" value="좋아요 취소">
              <i class="bi bi-hand-thumbs-up text-secondary"></i>
            </button>
        {% endif %}
      </form>

      <span class='d-flex align-items-end' style='font-size:20px;'>{{post.like_users.count}}</span>
      
    </h2>
    <span class="text-muted"
      >작성자:
      <a href="{% url 'accounts:profile' post.user.username %}"
        >{{ post.user.username }}</a
      ></span
    >
  </div>
  
  <div class="col-sm-4 d-flex align-items-center justify-content-end">
    {% if request.user == post.user %}
      <a href="{% url 'posts:update' post.pk %}" class="btn btn-outline-success mx-1 align-self-center btn-sm">수정</a>
      <form method="POST" action="{% url 'posts:delete' post.pk %}">
        {% csrf_token %}
        <input type="submit" value="삭제" class="btn btn-outline-danger btn-sm mx-1 align-self-center" />
      </form>
    {% endif %}
    <a href="{% url 'posts:index' %}" class="btn btn-outline-primary mx-1 btn-sm">뒤로 가기</a>
  </div>

</div>

{% comment %}
<form action="{% url 'posts:answer' post.pk %}" method="POST">
  <input type="submit" {{ post.select1_content }} />
  <input type="submit" {{ post.select2_content }} />
</form>
{% endcomment %} {% comment %}
<p>{{ post.select1_content }}: {{ post.select1_users }}</p>
<p>{{ post.select2_content }}: {{ post.select2_users }}</p>
{% endcomment %}

<div class="row align-items-center justify-content-center">
  <div class="col-md-5 d-flex justify-content-end">
    <div class="card" style="width: 100%">
      <div class="card-body text-center p-0">
        <!-- 이미지 -->
        {% if post.image1 %}
          <img src="{{ post.image1.url }}" alt="img1" style="width: 100%">
        {% else %}
          <img style ='width:100%' src="{% static 'no-photo.png' %}" alt="no-img">
        {% endif %}
      </div>
      <form
        method="POST"
        action="{% url 'posts:answer' post.pk 'select1' %}">
        {% csrf_token %}
        <div class="card-footer text-center p-0">
          <a href="{% url 'posts:detail' post.pk %}">
            <input
              type="submit"
              class="border-0 w-100 bg-transparent card-footer-input"
              value="{{ post.select1_content }} - {{ post.select1_users.count }}명"
            />
          </a>
        </div>
      </form>
    </div>
  </div>
  <div class="col-md-2">
    <h2 class="text-center">VS</h2>
  </div>
  <div class="col-md-5">
    <div class="card" style="width: 100%">
      <div class="card-body text-center p-0">
        <!-- 이미지 -->
        {% if post.image2 %}
          <img src="{{ post.image2.url }}" alt="image2" style="width: 100%">
        {% else %}
          <img style ='width:100%' src="{% static 'no-photo.png' %}" alt="no-img">
        {% endif %}
      </div>
      <form
        method="POST"
        action="{% url 'posts:answer' post.pk 'select2' %}"
      >
        {% csrf_token %}
        <div class="card-footer text-center p-0">
          <a href="{% url 'posts:detail' post.pk %}">
            <input
              type="submit"
              class="border-0 w-100 bg-transparent card-footer-input"
              value="{{ post.select2_content }} - {{ post.select2_users.count }}명"
            />
          </a>
        </div>
      </form>
    </div>
  </div>
</div>
<div>
<h5 class="mt-3">댓글 목록</h5>
<div>댓글 개수: {{ post.comment_set.count }}</div>
<div class="mt-3 mb-2">
  <form action="{% url 'posts:comment_create' post.pk %}" method="POST">
    {% csrf_token %} {{ comment_form.content }}
    <input
      type="submit"
      value="작성"
      class="btn btn-outline-primary btn-sm"
    />
  </form>
</div>

{% for comment in comments %}
<li class="comment-item mb-1" style="list-style: none">
  <div class="comment-author">
    <a class='mb-4' href="{% url 'accounts:profile' comment.user.username %}"
      >{{ comment.user.username }}</a
    >: {{ comment.content }}
    <div class='d-flex'>

      <div class='d-flex align-items-end'>
        <form action="{% url 'posts:comment_likes' post.pk comment.pk %}" method="POST">
          {% csrf_token %}
          {% if request.user in comment.like_users.all %}
            <button id='like_btn' class="border-0 bg-transparent text-danger" type='submit'>
              <i class="bi bi-heart-fill"></i>
            </button>
          {% else %}
            <button id='like_btn' class="border-0 bg-transparent" type='submit'>
              <i class="bi bi-heart"></i>
            </button>
          {% endif %}
        </form>

        <span class='ms-1' style='font-size:13px;'>{{comment.like_users.count}}</span>

        {% if request.user.is_authenticated and request.user == comment.user %}
          
          <form action="{% url 'posts:comment_delete' post.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input
              type="submit"
              value= " 삭제"
              class="border-0 bg-transparent text-secondary"
              style='font-size : 13px; font-weight:bold;'
            />
          </form>
        {% endif %}
      </div>
      
    </div>
  </div>
</li>
{% endfor %}


{% endblock body %}

Django/django-project/PJT-04(balance-game)/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}index{% endblock title %}
{% block body %}

    <h2 class="mb-3">🤝 밸런스 게임</h2>
    <a href="{% url 'posts:create' %}">
      <button class="btn btn-outline-primary mb-3">밸런스 게임 생성</button>
    </a>
    <div class="row">
      {% for post in posts %}
      <div class="col-md-3 col-sm-6 p-1 ">
        <div class="card mb-1 g-0">
          <a href="{% url 'posts:detail' post.pk %}">
            <div class="card-body text-center d-flex flex-column align-items-center">
              <div class="mx-1 mb-1">
                {{ post.title }}
              </div>
              <div class="d-flex justify-content-center flex-wrap">
                <div class="me-3 mb-2" style="font-size: 15px">
                  👍{{ post.like_users.count }}
                </div>
                <div class="mb-2" style="font-size: 15px">
                  💬{{ post.comment_set.all|length }}
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
      {% endfor %}
    </div> 
    
{% endblock body %}

Django/django-project/PJT-04(balance-game)/posts/templates/posts/update.html
{% extends 'base.html' %}
{% block title %}밸런스 게임 수정{% endblock title %}
{% block style %}
{% endblock style %} 
{% block body %}
<h2 class="mb-3">🎮 밸런스 게임 수정</h2>
<form
  action="{% url 'posts:update' post.pk %}"
  method="POST"
  enctype="multipart/form-data"
>
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="수정" class="btn btn-outline-primary" />
</form>
{% endblock body %}