Django/django-practice/Django_practice_0329/practices/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

Django/django-practice/Django_practice_0329/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
]

Django/django-practice/Django_practice_0329/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=True)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

Django/django-practice/Django_practice_0329/todos/views.py
from django.shortcuts import render
from .models import Todo
# Create your views here.
def index(request):
    todo = Todo.objects.all()
    context = {
        'todo': todo
    }
    return render(request, 'todos/index.html', context)


def new(request):
    return render(request, 'todos/new.html')


def create(request):
    title = request.GET.get('title')
    content = request.GET.get('content')
    priority = request.GET.get('priority')
    deadline = request.GET.get('deadline')
    todo = Todo(title=title, content=content, priority=priority, deadline=deadline)
    todo.save()
    return render(request, 'todos/create.html')


def detail(request, pk):
    todo = Todo.objects.get(pk=pk)
    context = {
        'todo': todo
    }
    return render(request, 'todos/detail.html', context)

Django/django-practice/Django_practice_0329/todos/templates/todos/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="container m-3">
    <h3>할 일이 입력되었습니다.</h3>
    <br>
    <a href="{% url 'todos:index' %}">
      <button type="button" class="btn btn-outline-primary">메인 화면으로 가기</button>
    </a>
  </div>
  
{% endblock content %}

Django/django-practice/Django_practice_0329/todos/templates/todos/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container m-3">
    <h3>할 일 제목: {{ todo.title}}</h3>
    <p>할 일 내용: {{ todo.content }}</p>
    <p>우선순위: {{ todo.priority }}</p>
    <p>마감기한: {{ todo.deadline }}</p>
    <a href="{% url 'todos:index' %}">
      <button type="button" class="btn btn-outline-primary">메인 화면으로 가기</button>
    </a>
  </div>
{% endblock content %}

Django/django-practice/Django_practice_0329/todos/templates/todos/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="container m-3">
    {% for thing  in todo  %}
    <div>
      <a href="{% url 'todos:detail' thing.pk %}">{{ thing.title }}</a>
    </div>
    {% endfor %}
    <br>
    <a href="{% url 'todos:new' %}">
      <button type="button" class="btn btn-outline-primary">할 일 추가하기</button>
    </a>
  </div>
  
{% endblock content %}

Django/django-practice/Django_practice_0329/todos/templates/todos/new.html
{% extends 'base.html' %}

{% block content %}
  <div class='container'>
    <form action="{% url 'todos:create' %}" method="GET">
      <div class="m-3">
        <label for="title">할 일 제목</label><br>
        <input type="text" name="title" id="title">
      </div>
      <div class="m-3">
        <label for="content">할 일 내용</label><br>
        <textarea name="content" id="content" cols="50" rows="10"></textarea>
      </div>
      <div class="m-3">
        <label for="priority">우선순위</label><br>
        <input type="number" name="priority" id="priority" min="1">
      </div>
      <div class="m-3">
        <label for="deadline">마감기한</label><br>
        <input type="date" name="deadline" id="deadline" value="2023-03-29">
      </div>  
      <div class="m-3">
        <input type="submit" value="할 일 생성" class="btn btn-outline-primary">
      </div>
    </form>
  </div>
{% endblock content %}