Django/django-project/PJT-02/CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

Django/django-project/PJT-02/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

Django/django-project/PJT-02/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('category/<str:subject>/', views.category, name='category'),
]

Django/django-project/PJT-02/accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    birthday = models.DateField(null=True, blank=True)

Django/django-project/PJT-02/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=False)
    category = models.CharField(max_length=20)
    deadline = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/django-project/PJT-02/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name','birthday', 'password1', 'password2')

    birthday = forms.DateField(
        label='생년월일',
        widget = forms.DateInput(
            attrs={'type': 'date'},
        ),
    )
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name','birthday')

    birthday = forms.DateField(
        label='생년월일',
        widget = forms.DateInput(
            attrs={'type': 'date'},
        ),
    )

Django/django-project/PJT-02/posts/forms.py
from django import forms
from .models import Post
from datetime import datetime

class PostForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'placeholder': '제목 입력칸',
                'class': 'form-control'
            }
        ),
        required=True
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'placeholder': '내용 입력',
                'class': 'my-content form-control'
            }
        ),
        required=True
    )
    category = forms.ChoiceField(
        label='카테고리',
        widget=forms.Select(
            attrs={
                'placeholder': '카테고리 입력',
                'class': 'form-select',
            }
        ),
        choices = (('개발','개발'), ('신기술', '신기술'), ('CS','CS')),
        required=True,
    )

    dt_now = datetime.today().strftime('%Y-%m-%d')
    deadline = forms.DateField(
        label='마감기한',
        widget=forms.DateInput(
            attrs={
                'class': 'form-control',
                'type': 'date',
                'value': dt_now,
            }
        ),
        required=True
    )

    class Meta:
        model = Post
        fields = '__all__'

Django/django-project/PJT-02/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash


# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect(request, 'posts:index')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('posts:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method =='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('posts:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context) 

Django/django-project/PJT-02/posts/views.py
from django.shortcuts import render, redirect
from .models import Post

from .forms import PostForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-pk')
    context = {
        'posts':posts,
    }
    return render(request, 'posts/index.html', context)


def detail(request, pk):
    post = Post.objects.get(pk=pk)
    context = {
        'post': post,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def create(request):

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)


@login_required
def update(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm(instance=post)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/update.html', context)


@login_required
def delete(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('posts:index')


def category(request, subject):
    subject = subject
    posts = Post.objects.filter(category=subject).order_by('-pk')
    context = {
        'subject': subject,
        'posts': posts,
    }
    return render(request, 'posts/category.html', context)

Django/django-project/PJT-02/accounts/templates/accounts/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400&family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk&display=swap" rel="stylesheet">



    
    {% block style %}
    {% endblock style %}
  </head>
  <style>
    html {
        height: 100%;
    }
    body {
      font-family: 'Space Grotesk', sans-serif;
      color: white;
      background-image: url(https://cdn.discordapp.com/attachments/1052100027297841152/1093772885170073722/pic.jpg);
        background-color: #D9E5FF;
        background-size: 100% 100%;
        border-radius: 2rem;
        object-fit: none;
        width: 100%;
        height: 100%;
        min-height: 100vh;
    }
    a {
      text-decoration: none;
      color: white;
    }
    .navbar {
    border-bottom: 1px solid white;
    display: flex;
    flex-wrap: nowrap;
    align-items: center;
    position: relative;
    justify-content: flex-end;
    padding: 0 1rem 5px;
    top: 0;
    }
    .sidebar {
    padding-bottom: 5px;
    display: inline-block;
    position: sticky;
    width: auto;
    height: auto;
    z-index: 1;
    top: 0;
    left:0;
    }
    .sidebar__list {
    list-style: none;
    padding: 5px;
    }
    .spread-underline {
            color: #333;
            text-decoration: none;
            /* display: inline-block; */
            /* padding: 15px 0; */
            position: relative;
            width: fit-content;
    }
    .spread-underline:after {    
            background: none repeat scroll 0 0 transparent;
            bottom: 0;
            content: "";
            display: block;
            height: 2px;
            left: 50%;
            position: absolute;
            background: #FF4500;
            transition: width 0.3s ease 0s, left 0.3s ease 0s;
            width: 0;
    }
    .spread-underline:hover:after {
            width: 100%;
            left: 0px;
    }
    *{
    margin: 0;
    margin: 0;
    box-sizing: border-box;
    }

    h3 {
        color: rgb(202, 202, 202);
        font-size: 23px;
        margin-bottom: 100px;
    }

    .clock {
        width: 170px;
        height: 170px;
        display: flex;
        justify-content: center;
        align-items: center;
        background-size: cover;
        border: 4px solid #1f1f1f;
        border-radius: 50%;
        box-shadow: 0 -15px 15px rgba(255, 255, 255, 0.05),
                    inset 0 -15px 15px rgba(255, 255, 255, 0.05),
                    0 15px 15px rgba(0, 0, 0, 0.3),
                    inset 0 15px 15px rgba(0, 0, 0, 0.3);
    }

    .clock:before {
        content: '';
        position: absolute ;
        width: 15px;
        height: 15px;
        background: #fff;
        border-radius: 50%;
        z-index: 1000;
    }

    .clock .hour,
    .clock .min, 
    .clock .sec {
        position: absolute;
    }

    .clock .hour, .hr{
        width: 70px;
        height: 80px;
    }

    .clock .min, .mn{
        width: 70px;
        height: 130px;
    }

    .clock .sec, .sc{
        width: 90px;
        height: 130px;
    }

    .hr, .mn, .sc {
        display: flex;
        justify-content: center;
        /* align-items: center; */
        position: absolute;
        border-radius: 50%;
    }

    .hr:before{
        content: '';
        position: absolute;
        width: 8px;
        height: 60px;
        background: #dfdfdf;
        z-index: 10;
        border-radius: 6px 6px 0 0;
    }

    .mn:before{
        content: '';
        position: absolute;
        width: 4px;
        height: 60px;
        background: #d6d6d6;
        z-index: 10;
        border-radius: 6px 6px 0 0;
    }

    .sc:before{
        content: '';
        position: absolute;
        width: 2px;
        height: 60px;
        background: rgb(121, 15, 15);
        z-index: 12;
        border-radius: 6px 6px 0 0;
    }
    .background {
        background-image: url(https://cdn.discordapp.com/attachments/1052100027297841152/1093772885170073722/pic.jpg);
        background-color: #D9E5FF;
        background-size: 100% 100%;
        border-radius: 2rem;
    }
  </style>
  <body>

    <div class="container-fluid">
        <header>
            <div class="container">
                <nav class="navbar mt-5 bg-body-primary">
                    <div class="container-fluid d-flex justify-content-start">
                        <a class="navbar-brand" href="{% url 'posts:index' %}">
                            <img src="https://cdn.discordapp.com/attachments/1052100027297841152/1093777273477398670/747589.png" alt="#" style="width:30px"> <span class="fs-6 align-bottom text-light">Home</span></a>
                    </div>
                    <div class="container-fluid d-flex justify-content-end">
                        <div class="d-flex me-3 text-light">
                        {% if request.user.is_authenticated %}
                        
                        {{ user.username }} 님 안녕하세요.
                        </div>
                        <div class="d-flex">
                        <form action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="로그아웃" class="text-light bg-transparent border-0 me-3">
                        </form>
                        <form action="{% url 'accounts:delete' %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="회원탈퇴" class="text-light bg-transparent border-0">
                        </form>
                        </div>
                    </div>
                        {% else %}
                        <div class="d-flex">
                            <a href="{% url 'accounts:signup' %}" class="me-5">Join</a>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </div>
                      
                      {% endif %}
                </nav>
            </div>
        </header>
        <main>
            <div class="container">
                <div class="row">
                    <div class="col-2">
                        <div class="container mt-5">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link disabled text-light">IT 정보공유</a>
                                </li>
                                <hr>
                                {% if request.user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link spread-underline text-light" href="{% url 'posts:create' %}">글 작성</a>
                                  </li>
                                {% endif %}
                                <li class="nav-item">
                                  <a class="nav-link spread-underline text-light" href="{% url 'posts:index' %}">모든글</a>
                                </li>
                                <li class="nav-item">
                                  <a class="nav-link spread-underline text-light" href="{% url 'posts:category' '개발' %}">개발</a>
                                </li>
                                <li class="nav-item">
                                  <a class="nav-link spread-underline text-light" href="{% url 'posts:category' 'CS' %}">CS</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link spread-underline text-light" href="{% url 'posts:category' '신기술' %}">신기술</a>
                                </li>
                            </ul>
                        </div>
                        <div class="clock mt-5">
                            <div class="hour">
                                <div class="hr" id="hr"></div>
                            </div>
                            <div class="min">
                                <div class="mn" id="mn"></div>
                            </div>
                            <div class="sec">
                                <div class="sc" id="sc"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-7 p-5">
                        <div class="container">
                        {% block content %}

                        {% endblock content %}
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous">
    </script>
     <script>
        const deg = 6;
        const hr = document.getElementById("hr");
        const mn = document.getElementById("mn");
        const sc = document.getElementById("sc");

        setInterval(() => {
            let day = new Date();
            let hh = day.getHours() * 30;
            let mm = day.getMinutes() * deg;
            let ss = day.getSeconds() * deg;
            console.log(hr);

            hr.style.transform = `rotateZ(${(hh)+(mm/12)}deg)`;
            mn.style.transform = `rotateZ(${mm}deg)`;
            sc.style.transform = `rotateZ(${ss}deg)`;
        })

    </script>
  </body>
</html>

Django/django-project/PJT-02/accounts/templates/accounts/change_password.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="container-fluid d-flex justify-content-end me-5 mt-3">
        <input type="submit" class="btn btn-light">
    </div>
</form>
{% endblock content %}

Django/django-project/PJT-02/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container d-flex justify-content-center">
  <div class="container">
    <h1 class='text-center mt-3'>로그인</h1>
  </div>
  <div class="container">
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {% for field in form  %}
        <div calss="input-group">
            <div class="input-gourp-text" id="{{ field.auto_id }}">{{ field.label }}</div>
            {{ field }}
        </div>
        <br>
        {% endfor %}
        <div class="container-fluid d-flex justify-content-center ms-5 mt-1">
            <input type="submit" class="btn btn-light"  role="button">
        </div>
    </form>
  </div>
</div>
{% endblock content %}

Django/django-project/PJT-02/accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container d-flex justify-content-center">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a href="#" class="fs-5 ms-3 text-light">회원가입</a>
        </li>
        <li class="nav-item">
        <form action="{% url 'accounts:signup' %}" method="POST" class="nav-link text-light">
            {% csrf_token %}
            {{ form.as_p }}
        <div class="container-fluid d-flex justify-content-end me-5 mt-3">
            <input type="submit" class="btn btn-light">
        </div>
        </form>
        </li>
    </ul>
</div>
{% endblock content %}

Django/django-project/PJT-02/accounts/templates/accounts/update.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1>회원 정보 수정</h1>
<form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="container-fluid d-flex justify-content-end me-5 mt-3">
        <input type="submit" class="btn btn-outline-primary">
    </div>
</form>
{% endblock content %}